name: Actor Core

on:
  push:
    branches: [ main ]
    paths:
    - "*/rust/**"
  pull_request:
    branches: [ main ]
    paths:
    - "*/rust/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  get_actors:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-actor-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: Build actor map
      id: set-actor-matrix
      run: |
        output=$(ls -d -1 */ | while read line; do echo \"$line\"; done | tr '\n' ',' | sed -e 's/^ //' -e 's/,$//' | (read; echo [$REPLY]))
        echo "::set-output name=matrix::$output"
  view_output:
    runs-on: ubuntu-latest
    needs: get_actors
    steps:
    - name: Output Matrix
      run: echo ${{ needs.get_actors.outputs.matrix }}

  cargo_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        actors: ${{ fromJson(needs.get_actors.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ needs.get_actors.outputs.matrix }}/rust
    - name: Run tests
      run: cargo test --features "guest" --verbose
      working-directory: ${{ needs.get_actors.outputs.matrix }}/rust
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ needs.get_actors.outputs.matrix }}/rust
    - run: rustup component add clippy
    - name: Run cargo clippy
      run: cargo clippy --all-features
      working-directory: ${{ needs.get_actors.outputs.matrix }}/rust
